version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./sites:/var/www
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    volumes:
      - ./sites:/var/www
    networks:
      - appnet
  mysql:
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=docker_app"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8183:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
      PMA_ARBITRARY: 1
    networks:
      - appnet
  redis:
    image: redis
    ports:
      - "63791:6379"
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
